-- BASE DE DATOS
CREATE DATABASE USER COLLATE 'utf8_general_ci';
-- TABLAS
CREATE TABLE USERS (ID INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(50));
CREATE TABLE CATEGORIAS (COD INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(50), DESCRIPCION VARCHAR(50), ESTADO BOOLEAN);
CREATE TABLE PRODUCTOS (COD INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(50), DESCRIPCION VARCHAR(50), CANTIDAD INT(4), SIZE VARCHAR(50), FOTO BLOB, COD_CATEGORIA INT(4), FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIAS (COD));
-- PROCEDIMIENTOS ALMACENADOS TABLA USER
-- INSERTAR
BEGIN
	INSERT INTO USERS ( NAME ) VALUES ( _NAME );
END;
-- MOSTRAR UNO
BEGIN
	SELECT ID, NAME FROM USERS WHERE ID = _ID;
END;
-- MOSTRAR TODO
BEGIN
	SELECT ID, NAME FROM USERS;
END;
-- ACTUALIZAR
BEGIN
	UPDATE USERS SET NAME = _NAME WHERE ID = _ID;
END;
-- BORRAR
BEGIN
	DELETE FROM USERS WHERE ID = _ID;
END 

-- PROCEDIMIENTOS ALMACENADOS PRODUCTOS
-- INSERTAR
BEGIN
	INSERT INTO PRODUCTO ( NAME, DESCRIPCION, CANTIDAD, SIZE, FOTO ) VALUES ( _NAME, _DES, _AMOUNT, _SIZE, _PHOTO);
END;
-- MOSTRAR UNO
BEGIN
	SELECT COD, NAME, DESCRIPCION, CANTIDAD, SIZE, FOTO FROM PRODUCTO WHERE COD = _COD;
END;
-- MOSTRAR TODO
BEGIN
	SELECT COD, NAME, DESCRIPCION, CANTIDAD, SIZE, FOTO FROM PRODUCTO;
END;
-- ACTUALIZAR
BEGIN
	UPDATE PRODUCTO SET NAME = _NAME WHERE COD = _COD;
END;
-- BORRAR
BEGIN
	DELETE FROM PRODUCTOS WHERE COD = _COD;
END 


-- SCRIPTS USUARIOS

-- INSERTAR
CREATE PROCEDURE `spInsertUser`(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN INSERT INTO USERS ( NAME ) VALUES ( _NAME ); END;
-- MOSTRAR UNO

-- MOSTRAR TODO
CREATE PROCEDURE `spFindAllUsers`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN SELECT ID, NAME FROM USERS; END;
-- ACTUALIZAR
CREATE PROCEDURE `spUpdateUser`(IN `_ID` INT(5), IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN UPDATE USERS SET NAME = _NAME WHERE ID = _ID; END;
-- BORRAR
CREATE PROCEDURE `spDeleteUser`(IN `ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN DELETE FROM USERS WHERE ID = _ID; END


-- SCRIPTS PRODUCTOS

-- INSERTAR
CREATE PROCEDURE `spInsertProducto`(IN `_NAME` VARCHAR(50), IN `_DES` VARCHAR(50), IN `_AMOUNT` INT(4), IN `_SIZE` VARCHAR(50), IN `_PHOTO` BLOB) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN INSERT INTO PRODUCTO ( NAME, DESCRIPCION, CANTIDAD, SIZE, FOTO ) VALUES ( _NAME, _DES, _AMOUNT, _SIZE, _PHOTO); END;


-- LLAMADO DE DEL SCRIPT
CALL spInsertUser('DEIMER');
CALL spFindAllUsers();
CALL spFindUser(1);
CALL spUpdateUser(1);
CALL spDeleteUser(2);


spInsertUser
spUpdateUser
spDeleteUser
spFindUser
spFindAllUsers